/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas;

/**
 *
 * @author Yisus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        btnLogOut.setBackground(new java.awt.Color(0,0,0,0));
        btnAcercaDe.setBackground(new java.awt.Color(0,0,0,0));
        btnRegistroPc.setBackground(new java.awt.Color(0,0,0,0));
        btnControlAlumnos.setBackground(new java.awt.Color(0,0,0,0));
        btnSoftwares.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        btnControlAlumnos = new javax.swing.JButton();
        btnRegistroPc = new javax.swing.JButton();
        btnSoftwares = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 0, 80, 70));

        btnAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 240, 230));

        btnControlAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnControlAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnControlAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, 220));

        btnRegistroPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPcActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 230, 220));

        btnSoftwares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSoftwares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoftwaresActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoftwares, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 240, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Blue White Illustration Website Launch Plan Presentation (2).gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que permite agregar un evento al boton LogOut que permite regresar a la interfaz gráfica de Login. 
     * @param evt 
     */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * Método que permite agregar un evento al boton Acerca que permite visualizar la interfaz gráfica AcercaDe. 
     * @param evt 
     */
    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        // TODO add your handling code here:
        AcercaDe ad = new AcercaDe();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    /**
     * Método que permite agregar un evento al boton ControlAlumnos que permite visualizar la interfaz gráfica InformaciónAlumnos.
     * @param evt 
     */
    private void btnControlAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlAlumnosActionPerformed
        // TODO add your handling code here:
        InformacionAlumnos ia = new InformacionAlumnos();
        ia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnControlAlumnosActionPerformed

    /**
     * Método que perminte agregar un evento al boton RegistroPc que permite visualizar la interfaz gráfica RegistroPc.
     * @param evt 
     */
    private void btnRegistroPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPcActionPerformed
        // TODO add your handling code here:
        RegistroPc rpc = new RegistroPc();
        rpc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroPcActionPerformed

    /**
     * Método que permite agregar un evento al boton Softwares que permite visualizar la interfaz gráfica SofwaresUsados.
     * @param evt 
     */
    private void btnSoftwaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoftwaresActionPerformed
        // TODO add your handling code here:
        
        SoftwaresUsados su = new SoftwaresUsados();
        su.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnSoftwaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnControlAlumnos;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRegistroPc;
    private javax.swing.JButton btnSoftwares;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
