/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Yisus
 */
public class RegistroPc extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPc
     */
    RegistroPcBackEnd rpc = new RegistroPcBackEnd();
    public RegistroPc() {
        initComponents();
        txtMatricula.setBackground(new java.awt.Color(0,0,0,0));
        btnAceptar.setBackground(new java.awt.Color(0,0,0,0));
        btnRegresar.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        tbtnWord = new javax.swing.JToggleButton();
        tbtnArduino = new javax.swing.JToggleButton();
        tbtnChrome = new javax.swing.JToggleButton();
        tbtnApache = new javax.swing.JToggleButton();
        tbtnCodeBlocks = new javax.swing.JToggleButton();
        tbtnExcel = new javax.swing.JToggleButton();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMatricula.setBorder(null);
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 400, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computadora 1", "Computadora 2", "Computadora 3", "Computadora 4", "Computadora 5", "Computadora 6", "Computadora 7", "Computadora 8", "Computadora 9", "Computadora 10", "Computadora 11", "Computadora 12", "Computadora 13", "Computadora 14", "Computadora 15", "Computadora 16", "Computadora 17", "Computadora 18", "Computadora 19", "Computadora 20", "Computadora 21", "Computadora 22", "Computadora 23", "Computadora 24", "Computadora 25", "Computadora 26", "Computadora 27", "Computadora 28", "Computadora 29", "Computadora 30", "Computadora 31", "Computadora 32", "Computadora 33", "Computadora 34", "Computadora 35", "Computadora 36", "Computadora 37", "Computadora 38", "Computadora 39", "Computadora 40" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 50));

        tbtnWord.setText("Word");
        tbtnWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnWordActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, 50));

        tbtnArduino.setText("Arduino");
        tbtnArduino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnArduinoActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnArduino, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 130, 50));

        tbtnChrome.setText("Chrome");
        tbtnChrome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnChrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnChromeActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnChrome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 130, 50));

        tbtnApache.setText("Apache NetBeans");
        tbtnApache.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnApache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnApacheActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnApache, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 130, 50));

        tbtnCodeBlocks.setText("CodeBlocks");
        tbtnCodeBlocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnCodeBlocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnCodeBlocksActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnCodeBlocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 50));

        tbtnExcel.setText("Excel");
        tbtnExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnExcelActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 293, 130, 50));

        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 110, 30));

        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Apellidos (3).gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 600, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 610, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String leerMatricula() {
        try {
            String codigo = txtMatricula.getText().trim();
            return codigo;
        } catch (Exception ex) {
            return null;
        }
    }
    

    
    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tbtnWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnWordActionPerformed

    private void tbtnArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnArduinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnArduinoActionPerformed

    private void tbtnChromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnChromeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnChromeActionPerformed

    private void tbtnCodeBlocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCodeBlocksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnCodeBlocksActionPerformed

    private void tbtnApacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnApacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnApacheActionPerformed

    private void tbtnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnExcelActionPerformed

    /**
     * Método que agrega un evento al boton Aceptar que verifica si se ha ingresado una matrícula válida, verifica si la matrícula existe en el sistema, guarda el registro con la fecha actual, la matrícula, el equipo y el software seleccionados.
     * @param evt 
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
       String matricula = leerMatricula();
       if (matricula == null || matricula.isEmpty()) {
           rpc.mensaje("Ingresar Matricula");
       } 
       else {
           if (rpc.verificarMatricula(matricula)) {
               String equipo = jComboBox1.getSelectedItem().toString();
               String software = "";
               if (tbtnWord.isSelected()) {
                   software += "Word, ";
               }
               if (tbtnArduino.isSelected()) {
                   software += "Arduino, ";
               }
               if (tbtnChrome.isSelected()) {
                   software += "Chrome, ";
               }
               if (tbtnApache.isSelected()) {
                   software += "NetBeans, ";
               }
               if (tbtnCodeBlocks.isSelected()) {
                   software += "CodeBlocks, ";
               }
               if (tbtnExcel.isSelected()) {
                   software += "Excel,";
               }
               Date f = new Date();
               rpc.guardarRegistro(f, matricula, equipo, software);
               rpc.mensaje("Registro guardado exitosamente.");
               Menu m = new Menu();
               m.setVisible(true);
               this.dispose();
           } 
           else {
               rpc.mensaje("La matricula no existe");
           }
       }
       

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Método que permite mostrar un mensaje para ciertos casos. 
     * @param texto 
     */
    public void mensaje(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
    
    /**
     * Método que permite agregar un evento al boton Regresar que permite visualizar la interfaz gráfica de Menu.
     * @param evt 
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPc().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton tbtnApache;
    private javax.swing.JToggleButton tbtnArduino;
    private javax.swing.JToggleButton tbtnChrome;
    private javax.swing.JToggleButton tbtnCodeBlocks;
    private javax.swing.JToggleButton tbtnExcel;
    private javax.swing.JToggleButton tbtnWord;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
