/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Yisus
 */
public class SoftwaresUsados extends javax.swing.JFrame {

    /**
     * Creates new form SoftwaresUsados
     */
    public SoftwaresUsados() {
        initComponents();
        btnAceptar.setBackground(new java.awt.Color(0,0,0,0));
        btnRegresar.setBackground(new java.awt.Color(0,0,0,0));
        txtWord.setBackground(new java.awt.Color(0,0,0,0));
        txtArduino.setBackground(new java.awt.Color(0,0,0,0));
        txtExcel.setBackground(new java.awt.Color(0,0,0,0));
        txtNetBeans.setBackground(new java.awt.Color(0,0,0,0));
        txtChrome.setBackground(new java.awt.Color(0,0,0,0));
        txtNetBeans.setBackground(new java.awt.Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWord = new javax.swing.JTextField();
        txtExcel = new javax.swing.JTextField();
        txtArduino = new javax.swing.JTextField();
        txtNetBeans = new javax.swing.JTextField();
        txtCodeBlocks = new javax.swing.JTextField();
        txtChrome = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWord.setBackground(new java.awt.Color(255, 255, 255));
        txtWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWord.setBorder(null);
        txtWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWordActionPerformed(evt);
            }
        });
        getContentPane().add(txtWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 40, 30));

        txtExcel.setBackground(new java.awt.Color(255, 255, 255));
        txtExcel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtExcel.setBorder(null);
        txtExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExcelActionPerformed(evt);
            }
        });
        getContentPane().add(txtExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 40, 30));

        txtArduino.setBackground(new java.awt.Color(255, 255, 255));
        txtArduino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArduino.setBorder(null);
        txtArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArduinoActionPerformed(evt);
            }
        });
        getContentPane().add(txtArduino, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 40, 30));

        txtNetBeans.setBackground(new java.awt.Color(255, 255, 255));
        txtNetBeans.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNetBeans.setBorder(null);
        txtNetBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetBeansActionPerformed(evt);
            }
        });
        getContentPane().add(txtNetBeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 40, 30));

        txtCodeBlocks.setBackground(new java.awt.Color(255, 255, 255));
        txtCodeBlocks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodeBlocks.setBorder(null);
        txtCodeBlocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeBlocksActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodeBlocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 345, 40, -1));

        txtChrome.setBackground(new java.awt.Color(255, 255, 255));
        txtChrome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChrome.setBorder(null);
        txtChrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChromeActionPerformed(evt);
            }
        });
        getContentPane().add(txtChrome, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 40, 30));

        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 40));

        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Apellidos (4).gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExcelActionPerformed

    private void txtArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArduinoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtArduinoActionPerformed

    private void txtNetBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetBeansActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNetBeansActionPerformed

    private void txtCodeBlocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeBlocksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeBlocksActionPerformed

    private void txtChromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChromeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChromeActionPerformed

    private void txtWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtWordActionPerformed

    BackEndSoftwaresUsados rp = new BackEndSoftwaresUsados();
    
    /**
     * Método para agregar un evento al boton Aceptar que se encarga de leer l archivo "registros.txt" línea por línea, cuenta las apariciones de cada palabra clave en el archivo y muestra los conteos en campos de texto correspondientes en la interfaz gráfica.
     * @param evt 
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String filePath = "registros.txt";
        String[] palabras = { "Word", "Excel", "NetBeans", "CodeBlocks", "Chrome", "Arduino" };

        try {
            BufferedReader reader = new BufferedReader(new FileReader(filePath));
            String line;
            int[] conteos = new int[palabras.length];

            while ((line = reader.readLine()) != null) {
                for (int i = 0; i < palabras.length; i++) {
                    conteos[i] += rp.contarPalabra(line, palabras[i]);
                }
            }

            reader.close();
            for (int i = 0; i < palabras.length; i++) {
                switch (palabras[i]) {
                    case "Word":
                        txtWord.setText("" + conteos[i]);
                        break;
                    case "Excel":
                        txtExcel.setText("" + conteos[i]);
                        break;
                    case "NetBeans":
                        txtNetBeans.setText("" + conteos[i]);
                        break;
                    case "CodeBlocks":
                        txtCodeBlocks.setText("" + conteos[i]);
                        break;
                    case "Chrome":
                        txtChrome.setText("" + conteos[i]);
                        break;
                    case "Arduino":
                        txtArduino.setText("" + conteos[i]);
                        break;
                }
            }
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Método para agregar un evento al boton Regresar que permite visualizar la interfaz gráfica de Menu.
     * @param evt 
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoftwaresUsados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoftwaresUsados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoftwaresUsados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoftwaresUsados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoftwaresUsados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtArduino;
    private javax.swing.JTextField txtChrome;
    private javax.swing.JTextField txtCodeBlocks;
    private javax.swing.JTextField txtExcel;
    private javax.swing.JTextField txtNetBeans;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
